In [2]:
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
import pandas as pd
import os

import warnings
warnings.filterwarnings('ignore')

In [3]:
filepath = os.getcwd()+'/geckodriver.exe'
print('Path to Driver is '+filepath)

Path to Driver is C:\Users\COBENA\Desktop\Learn\Code\FTW\Capstone Idea\Automotive\Web Scraping/geckodriver.exe

In [4]:
df = pd.read_csv('C:\\Users\COBENA\Desktop\Learn\Code\FTW\Capstone Idea\Automotive\Web Scraping/to_scrape_retail_price.csv',index_col=None)
df.head()

       Brand     Model
0  Chevrolet   Captiva
1  Chevrolet     Optra
2  Chevrolet      Spin
3  Chevrolet  Corvette
4  Chevrolet      Aveo

In [6]:
browser=webdriver.Firefox(executable_path=filepath)

In [7]:
model=[x for x in df['Model']]
brand=[x for x in df['Brand']]
count=0
skip=0
for x, y in zip(brand,model):
    x=str(x.strip().lower())
    y=str(y.strip().lower())
    browser.get('https://www.zigwheels.ph/new-cars/'+x+'/'+y+'/price')
    try:
        zig_srp=WebDriverWait(browser,5).until(EC.presence_of_element_located((By.XPATH,'/html/body/main/div[1]/div/div[1]/div[1]/ul/li[1]/div[2]'))).text
        zig_amt=WebDriverWait(browser,5).until(EC.presence_of_element_located((By.XPATH,'/html/body/main/div[1]/div/div[1]/div[1]/ul/li[3]/div[2]'))).text
        count+=1
        print(count)
    except:
        skip+=1
        print('skipped',skip)
    df=df.append({'zig_srp':zig_srp,'zig_amt':zig_amt,'x':x,'y':y},ignore_index=True)
    df=df[['x','y','zig_srp','zig_amt']]
print('done')

1
skipped 1
skipped 2
2
skipped 3
skipped 4
skipped 5
skipped 6
skipped 7
skipped 8
skipped 9
skipped 10
skipped 11
skipped 12
skipped 13
skipped 14
skipped 15
skipped 16
skipped 17
skipped 18
skipped 19
skipped 20
skipped 21
skipped 22
skipped 23
skipped 24
3
skipped 25
skipped 26
skipped 27
skipped 28
skipped 29
skipped 30
4
skipped 31
5
skipped 32
skipped 33
skipped 34
skipped 35
skipped 36
skipped 37
skipped 38
skipped 39
skipped 40
skipped 41
skipped 42
6
skipped 43
skipped 44
skipped 45
7
8
9
skipped 46
10
skipped 47
skipped 48
skipped 49
skipped 50
skipped 51
skipped 52
skipped 53
skipped 54
skipped 55
skipped 56
skipped 57
11
skipped 58
skipped 59
skipped 60
12
skipped 61
13
skipped 62
skipped 63
skipped 64
14
skipped 65
skipped 66
skipped 67
skipped 68
skipped 69
skipped 70
skipped 71
skipped 72
15
skipped 73
skipped 74
skipped 75
skipped 76
skipped 77
skipped 78
skipped 79
skipped 80
skipped 81
skipped 82
skipped 83
skipped 84
skipped 85
skipped 86
skipped 87
skipped 88
skipped 89
skipped 90
16
17
18
skipped 91
skipped 92
skipped 93
19
20
skipped 94
skipped 95
skipped 96
skipped 97
skipped 98
skipped 99
skipped 100
21
skipped 101
skipped 102
skipped 103
skipped 104
skipped 105
skipped 106
22
skipped 107
skipped 108
23
skipped 109
skipped 110
skipped 111
skipped 112
skipped 113
skipped 114
skipped 115
skipped 116
skipped 117
skipped 118
skipped 119
skipped 120
skipped 121
skipped 122
skipped 123
skipped 124
skipped 125
skipped 126
skipped 127
skipped 128
skipped 129
skipped 130
skipped 131
skipped 132
skipped 133
skipped 134
skipped 135
skipped 136
skipped 137
skipped 138
skipped 139
skipped 140
skipped 141
skipped 142
skipped 143
skipped 144
24
skipped 145
skipped 146
skipped 147
skipped 148
skipped 149
skipped 150
skipped 151
skipped 152
skipped 153
skipped 154
skipped 155
skipped 156
skipped 157
skipped 158
skipped 159
skipped 160
skipped 161
skipped 162
skipped 163
skipped 164
skipped 165
25
skipped 166
skipped 167
skipped 168
skipped 169
skipped 170
skipped 171
skipped 172
skipped 173
skipped 174
skipped 175
skipped 176
skipped 177
skipped 178
skipped 179
skipped 180
skipped 181
skipped 182
skipped 183
skipped 184
skipped 185
skipped 186
26
skipped 187
done